# Generated by Django 4.2.7 on 2025-10-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=models.CharField(help_text='Your admission batch (e.g., Fall 2023, Spring 2024)', max_length=20),
        ),
    ]
