# Generated by Django 4.2.7 on 2025-10-19 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a valid Green University email (format: 252006089@student.green.ac.bd)', regex='^\\d{9}@student\\.green\\.ac\\.bd$')]),
        ),
    ]
